<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/human_skull.glb
Author: roxyjungle (https://sketchfab.com/roxyjungle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-skull-free-7081b32caeda47b5a0ef4d039f244b6e
Title: Human skull FREE
-->

<script>
	//
	// ╭━━╮╱╱╱╱╭╮╱╱╱╱╱╭╮╱╭╮╱╱╱╱╱╭╮            ━╮ ╭━
	// ╰┫┣╯╱╱╱╱┃┃╱╱╱╱╭╯╰╮┃┃╱╱╱╱╱┃┃             | |
	// ╱┃┃╭━╮╭━╯┣━━┳━┻╮╭╯┃┃╱╱╭━━┫╰━┳━━╮       ╱ o \
	// ╱┃┃┃╭╮┫╭╮┃┃━┫━━┫┃╱┃┃╱╭┫╭╮┃╭╮┃━━┫      ╱_____\
	// ╭┫┣┫┃┃┃╰╯┃┃━╋━━┃╰╮┃╰━╯┃╭╮┃╰╯┣━━┃     ╱    o  \
	// ╰━━┻╯╰┻━━┻━━┻━━┻━╯╰━━━┻╯╰┻━━┻━━╯    (__o______)

	// Yet another science experiment from Indest Labs.

	// Recommend viewing in Visual Source Code.
	//
	import { Group } from 'three'
	import { T, forwardEventHandlers } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	export const ref = new Group()

	const gltf = useGltf('/human_skull.glb')

	const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[0, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={1.3}>
			<T.Mesh
				geometry={gltf.nodes.Object_3.geometry}
				material={gltf.materials.SKULLhighCLEANEDdefaultMat}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_4.geometry}
				material={gltf.materials.SKULLhighCLEANEDdefaultMat}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_5.geometry}
				material={gltf.materials.SKULLhighCLEANEDdefaultMat}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_6.geometry}
				material={gltf.materials.SKULLhighCLEANEDdefaultMat}
			/>
			<T.Mesh
				geometry={gltf.nodes.Object_7.geometry}
				material={gltf.materials.SKULLhighCLEANEDdefaultMat}
			/>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
